# Generated by Django 5.2.7 on 2025-12-09 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mahasiswa', '0002_mahasiswa_alamat_mahasiswa_jurusan_mahasiswa_no_hp'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mahasiswa',
            options={'verbose_name': 'Mahasiswa', 'verbose_name_plural': 'Mahasiswas'},
        ),
        migrations.RenameField(
            model_name='mahasiswa',
            old_name='no_hp',
            new_name='nohp',
        ),
        migrations.RemoveField(
            model_name='mahasiswa',
            name='alamat',
        ),
        migrations.AlterField(
            model_name='mahasiswa',
            name='nama',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='mahasiswa',
            name='npm',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
